module.exports = {
  apps: [
    {
      name: "siqueira-main",
      script: "dist/server/node-build.mjs",
      cwd: "/opt/siqueira-campos",
      instances: 2,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
        SUBDOMAIN: "main",
      },
      env_production: {
        NODE_ENV: "production",
        PORT: 3000,
      },
      error_file: "/opt/siqueira-campos/logs/main-error.log",
      out_file: "/opt/siqueira-campos/logs/main-out.log",
      log_file: "/opt/siqueira-campos/logs/main-combined.log",
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      min_uptime: "10s",
      max_restarts: 10,
    },
    {
      name: "siqueira-app",
      script: "dist/server/node-build.mjs",
      cwd: "/opt/siqueira-campos",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: 3002,
        SUBDOMAIN: "app",
      },
      env_production: {
        NODE_ENV: "production",
        PORT: 3002,
      },
      error_file: "/opt/siqueira-campos/logs/app-error.log",
      out_file: "/opt/siqueira-campos/logs/app-out.log",
      log_file: "/opt/siqueira-campos/logs/app-combined.log",
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      min_uptime: "10s",
      max_restarts: 10,
    },
    {
      name: "siqueira-cliente",
      script: "dist/server/node-build.mjs",
      cwd: "/opt/siqueira-campos",
      instances: 1,
      exec_mode: "cluster",
      env: {
        NODE_ENV: "production",
        PORT: 3003,
        SUBDOMAIN: "cliente",
      },
      env_production: {
        NODE_ENV: "production",
        PORT: 3003,
      },
      error_file: "/opt/siqueira-campos/logs/cliente-error.log",
      out_file: "/opt/siqueira-campos/logs/cliente-out.log",
      log_file: "/opt/siqueira-campos/logs/cliente-combined.log",
      time: true,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      min_uptime: "10s",
      max_restarts: 10,
    },
  ],

  deploy: {
    production: {
      user: "siqueira",
      host: ["siqueicamposimoveis.com.br"],
      ref: "origin/main",
      repo: "https://github.com/kryonix/siqueira-campos.git",
      path: "/opt/siqueira-campos",
      "pre-deploy-local": "",
      "post-deploy":
        "npm install && npm run build && pm2 reload ecosystem.config.js --env production",
      "pre-setup": "",
    },
  },
};
