version: "3.8"

# Stack para Portainer - Siqueira Campos Imóveis
# Para usar no Portainer: copie este arquivo e cole como nova stack

services:
  # Banco de Dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: bdsitejuarez
      POSTGRES_USER: sitejuarez
      POSTGRES_PASSWORD: juarez123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /opt/siqueira/backups:/backups
    networks:
      - siqueira-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Redis para Cache
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - siqueira-network
    command: redis-server --appendonly yes
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Aplicação Principal
  app:
    image: siqueira-campos:latest # Substituir pela imagem buildada
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://sitejuarez:juarez123@postgres:5432/bdsitejuarez?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
      - PORT=3000
      - MAIN_DOMAIN=siqueicamposimoveis.com.br
      - JWT_SECRET=468465454567653554546524
      - JWT_EXPIRES_IN=7d
      - COOKIE_SECRET=645454564867654575565
    volumes:
      - /opt/siqueira/uploads:/app/uploads
      - /opt/siqueira/logs:/app/logs
    networks:
      - siqueira-network
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.siqueira-app.rule=Host(`siqueicamposimoveis.com.br`) || Host(`www.siqueicamposimoveis.com.br`)"
        - "traefik.http.routers.siqueira-app.entrypoints=websecure"
        - "traefik.http.routers.siqueira-app.tls.certresolver=letsencrypt"
        - "traefik.http.services.siqueira-app.loadbalancer.server.port=3000"

  # N8N para Automação
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=sitejuarez
      - DB_POSTGRESDB_PASSWORD=juarez123
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=siqueira123
      - WEBHOOK_URL=https://n8n.siqueicamposimoveis.com.br
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - siqueira-network
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.siqueira-n8n.rule=Host(`n8n.siqueicamposimoveis.com.br`)"
        - "traefik.http.routers.siqueira-n8n.entrypoints=websecure"
        - "traefik.http.routers.siqueira-n8n.tls.certresolver=letsencrypt"
        - "traefik.http.services.siqueira-n8n.loadbalancer.server.port=5678"

  # Evolution API para WhatsApp
  evolution-api:
    image: davidsongomes/evolution-api:latest
    restart: unless-stopped
    environment:
      - SERVER_PORT=8080
      - CORS_ORIGIN=*
      - DEL_INSTANCE=false
      - DATABASE_CONNECTION_URI=postgresql://sitejuarez:juarez123@postgres:5432/evolution?schema=public
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - REDIS_URI=redis://redis:6379
      - AUTHENTICATION_API_KEY=siqueira_evolution_key_2024
      - LANGUAGE=pt-BR
    volumes:
      - evolution_data:/evolution/instances
      - evolution_store:/evolution/store
    networks:
      - siqueira-network
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.siqueira-whatsapp.rule=Host(`whatsapp.siqueicamposimoveis.com.br`)"
        - "traefik.http.routers.siqueira-whatsapp.entrypoints=websecure"
        - "traefik.http.routers.siqueira-whatsapp.tls.certresolver=letsencrypt"
        - "traefik.http.services.siqueira-whatsapp.loadbalancer.server.port=8080"

  # Backup Automático
  backup:
    image: prodrigestivill/postgres-backup-local:15
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=bdsitejuarez
      - POSTGRES_USER=sitejuarez
      - POSTGRES_PASSWORD=juarez123
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=30
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
    volumes:
      - /opt/siqueira/backups:/backups
    networks:
      - siqueira-network
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  n8n_data:
    driver: local
  evolution_data:
    driver: local
  evolution_store:
    driver: local

networks:
  siqueira-network:
    driver: overlay
    attachable: true
